name: Update CustomBlocklist

on:
  push:
    branches:
      - main
    paths:
      - FTL_URL.txt

permissions:
  contents: write

jobs:
  update-blocklist:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run blocklist update script
        run: |
          chmod +x update_blocklist.sh
          ./update_blocklist.sh

      - name: Commit changes if needed
        run: |
          # if git diff --quiet; then
          #   echo "No changes to commit"
          #   exit 0
          # fi
          NOW=$(date '+%Y-%m-%d %H:%M:%S')
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add CustomBlocklist1.txt
          git add CustomBlocklist2.txt
          git commit -m "Update CustomBlocklist [$NOW]"
          git push
